services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=Jogja,123
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    networks:
      - express_network
      
  db_testing:
    image: postgres
    container_name: postgres_testing_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=Jogja,123
    ports:
      - "7654:5432"

networks:
  express_network:
